[tool.poetry]
name = "django-getpaid"
version = "2.0.0-rc.3"
description = "Multi-broker payment processor for Django"
authors = ["Dominik Kozaczko <dominik@kozaczko.info>", "django-getpaid team"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
swapper = "^1.1"
requests = "^2.22"
pendulum = "^2.0"
django-model-utils = "^3.2"

[tool.poetry.dev-dependencies]
pre-commit = "^1.20"
sphinx = "^2.2"

[tool.black]
line-length = 88
target-version = ['py35']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.cache
    | \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | __pycache__
    | _build
    | buck-out
    | build
    | dist
    | docs
    | migrations
  )/

)
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = false
line_length = 88
known_first_party = ["getpaid", "factory", "orders"]
known_third_party = ["django", "pendulum", "requests", "swapper"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
